version: '3.4'

services:
  infra:
    build: .
    volumes:
      - .:/terraform
      - .terraform.d:/root/.terraform.d/
      - ~/.ssh/mini-apps-platform.pub:/terraform/terraform/live/cluster-prod/.ssh/mini-apps-platform.pub:ro
      - ~/.ssh/mini-apps-platform:/terraform/terraform/live/cluster-prod/.ssh/mini-apps-platform:ro
