helmDefaults:
  wait: true

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: wikimedia
    url: https://helm-charts.wikimedia.org/stable/

releases:
  - name: csi-driver
    namespace: csi-driver
    chart: wikimedia/raw
    values:
    - ./csi-driver/templates.yaml
    - ./csi-driver/raw-resources.yaml

  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    namespace: ingress-nginx
    version: 3.5.1

  - name: cert-manager
    version: 1.2.0
    namespace: cert-manager
    chart: jetstack/cert-manager
    set:
      - name: installCRDs
        value: true

  - name: issuers
    chart: wikimedia/raw
    namespace: cert-manager
    version: 0.2.5
    values:
      - ./cert-manager/raw-resources.yaml
